import type { Metadata } from "next";

import "./globals.css";
import Navbar from "./navbar/navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Inter } from "next/font/google";
import Footer from "./footer/footer";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}  md:text-[16px] text-[14px] font-medium`}
      >
        <Navbar/>{children}<Footer/>
      </body>
    </html>
  );
}
